# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coronaValon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coronaValon
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Analytics'
end
